version: "3.9"

services:

  bet-maker-db:
    image: postgres:12
    container_name: bet-maker-db
    restart: always
    command: postgres -c 'max_connections=1000' -c 'listen_addresses=*'
    volumes:
      - ./db_volumes/bet-maker/:/var/lib/${BET_MAKER_DB}/data
    ports:
      - "54321:5432"
    environment:
      POSTGRES_DB: ${BET_MAKER_DB}
      POSTGRES_USER: ${BET_MAKER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${BET_MAKER_POSTGRES_PASSWORD}

  bet-maker-migrations:
    build: bet_maker
    environment:
      POSTGRES_DB: ${BET_MAKER_DB}
      POSTGRES_USER: ${BET_MAKER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${BET_MAKER_POSTGRES_PASSWORD}
    depends_on:
      - bet-maker-db
    command: alembic upgrade head
    restart: on-failure:5

  bet-maker:
    build: bet_maker
    environment:
      POSTGRES_DB: ${BET_MAKER_DB}
      POSTGRES_USER: ${BET_MAKER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${BET_MAKER_POSTGRES_PASSWORD}
      SALT_BET_MAKER: ${SALT_BET_MAKER}
    volumes:
      - ./bet_maker/code:/code
    depends_on:
      - bet-maker-migrations

  redis-bet-maker:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  line-provider-db:
    image: postgres:12
    container_name: line-provider-db
    restart: always
    command: postgres -c 'max_connections=1000' -c 'listen_addresses=*'
    volumes:
      - ./db/line-provider:/var/lib/${LINE_PROVIDER_DB}/data
    ports:
      - "54322:5432"
    environment:
      POSTGRES_DB: ${LINE_PROVIDER_DB}
      POSTGRES_USER: ${LINE_PROVIDER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${LINE_PROVIDER_POSTGRES_PASSWORD}

  line-provider-migrations:
    build: line_provider
    environment:
      POSTGRES_DB: ${LINE_PROVIDER_DB}
      POSTGRES_USER: ${LINE_PROVIDER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${LINE_PROVIDER_POSTGRES_PASSWORD}
    depends_on:
      - line-provider-db
    command: alembic upgrade head
    restart: on-failure:5

  line-provider:
    build: line_provider
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SALT: ${SALT_LINE_PROVIDER}
    volumes:
      - ./line_provider/code:/code
    depends_on:
      - line-provider-migrations
    ports:
      - 8000:80

  proxy:
    image: nginx:1.20
    container_name: proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - bet-maker
      - line-provider
    volumes:
      - ./nginx:/etc/nginx/
