"""empty-initial

Revision ID: 379feb553db6
Revises: 
Create Date: 2022-08-29 04:35:24.216484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379feb553db6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bm_bet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('size', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('state', sa.Enum('NEW', 'WIN', 'LOSE', name='betstate'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bm_bet')
    # ### end Alembic commands ###
